### ISSUE TITLE
allow the markdown to be specified as plain node content?

### ISSUE THREAD

**Issue by Pomax** [rexxars/react-markdown#37]
Rather than extracting as `this.props.source`, it would be much nicer if we could just have the Markdown as normal content, and then have the component extract it from `this.props.children`.

**Comment by rexxars** [comment]
Sure. As long as it's backwards compatible, I'll accept a PR.

**Comment by pke** [comment]
here here. When I came across the library I was instantly thinking "why isn't it using `children` as the markdown body?"
I'd treat `children` as to be only one, a string, and not accept react elements inside it.

**Comment by rexxars** [comment]
Happy to accept a pull request.

**Comment by pke** [comment]
I am just thinking how the jsx compiler would treat this:

```jsx
<Markdown>What a **bold** move.</Markdown>
```

Will it have converted the text into chunks of `<span>`? Guess I have to try it to find out. Let the forking begin :)

**Comment by pke** [comment]
@rexxars Hmmm tried to run the tests before doing any dev to see if they are all green and got:

```
$ npm t

> react-markdown@2.5.0 test C:\dev\projects\react-markdown
> mocha --reporter spec



  ReactMarkdown
    1) "before all" hook


  0 passing (3s)
  1 failing

  1) ReactMarkdown "before all" hook:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at Object.done (node_modules\mocha-jsdom\index.js:70:7)
      at process.nextTick (node_modules\jsdom\lib\jsdom.js:325:18)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```
